add chapter 11 files

diff --git a/11_Functions_pt1/tests/runtests b/11_Functions_pt1/tests/runtests
--- a/11_Functions_pt1/tests/runtests
+++ b/11_Functions_pt1/tests/runtests
@@ -1,3 +1,4 @@
+#!/bin/sh
 # Run each test and compare
 # against known good output
 
@@ -7,19 +8,19 @@ fi
 
 for i in input*
 do if [ ! -f "out.$i" ]
-    then echo "Can't run test on $i, no output file!"
-    else
-        echo -n $i
-        ../comp1 $i
-        cc -o out out.s
-        ./out > trial.$i
-        cmp -s "out.$i" "trial.$i"
-        if [ "$?" -eq "1" ]
-        then echo ": failed"
-            diff -c "out.$i" "trial.$i"
-            echo
-        else echo ": OK"
-        fi
-        rm -f out out.s "trial.$i"
-    fi
+   then echo "Can't run test on $i, no output file!"
+   else
+     echo -n $i
+     ../comp1 $i
+     cc -o out out.s
+     ./out > trial.$i
+     cmp -s "out.$i" "trial.$i"
+     if [ "$?" -eq "1" ]
+     then echo ": failed"
+       diff -c "out.$i" "trial.$i"
+       echo
+     else echo ": OK"
+     fi
+     rm -f out out.s "trial.$i"
+   fi
 done
